# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A1BWbU2ayBYvMs_mYoY17sYtgHwN-6e-
"""

#!pip install streamlit
#!pip install pyngrok  # Tunneling tool to create a public URL for our local server

#!ngrok authtoken 
import os

os.environ['HF_TOKEN'] = 'Your hugging face token'


import streamlit as st
from transformers import AutoTokenizer, TFAutoModelForSeq2SeqLM

# Install required packages
st.title("Language Translation App")

# Model and tokenizer initialization
model_checkpoint = "Helsinki-NLP/opus-mt-en-hi"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
model = TFAutoModelForSeq2SeqLM.from_pretrained("/content/drive/MyDrive/sem_4/tf_model/")

# Input text area
input_text = st.text_area("Enter English Text:", "My name is Shivani. I am a student")

# Translate button
if st.button("Translate"):
    # Translate function
    tokenized = tokenizer([input_text], return_tensors='np')
    translated_ids = model.generate(**tokenized, max_length=128)

    # Decoding the translated text
    translated_text = tokenizer.decode(translated_ids[0], skip_special_tokens=True)

    # Display translated text
    st.write("Translated Hindi Text:")
    st.write(translated_text)